### create a new user

POST http://localhost:3000/auth/signin
content-type:application/json

{
    "email":"soheil.moonesi@gmail.com",
    "password":"123456",
    "name":"
}


### jwt token and find id 
GET http://localhost:3000/auth/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic29oZWlsLm1vb25lc2lAZ21haWwuY29tIiwiaWF0IjoxNjk2ODM4NjI5LCJleHAiOjE2OTY4Mzg2MzB9.0OiGId1WRbMF2bP93U-ueH-qa9HJXzNR4icxBeenjOs
Refresh: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic29oZWlsLm1vb25lc2lAZ21haWwuY29tIiwiZGlmZiI6InNzIiwiaWF0IjoxNjk2ODM5MDQ3LCJleHAiOjE2OTY4MzkzNDd9.LMrFMuDABr0vy7Ysep4GkguBDYZpsDKRlND_JDT9evs

### find with id

GET http://localhost:3000/auth/3


### test for hello world

GET http://localhost:3000


### find email

GET http://localhost:3000/auth?email=soheil@gmail.com

### delete by id

DELETE http://localhost:3000/auth/1

### patch by id

PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email":"reza@gmail.com"
}